name: mediapip_torch
channels:
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16
  - arrow=1.2.3
  - astroid=2.14.2
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=23.1.0
  - autopep8=2.0.4
  - babel=2.11.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.4.2
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.16.0
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cryptography=42.0.5
  - cuda-cccl=12.6.37
  - cuda-cccl_win-64=12.6.37
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.6.37
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.11.0
  - debugpy=1.6.7
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.8
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.6.2
  - filelock=3.13.1
  - flake8=7.0.0
  - fontconfig=2.14.2
  - fonttools=4.51.0
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.2
  - glib-tools=2.80.2
  - graphite2=1.3.14
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=7.0.1
  - inflection=0.5.1
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - ipywidgets=8.1.2
  - isort=5.13.2
  - jaraco.classes=3.2.1
  - jedi=0.19.1
  - jellyfish=1.0.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.10
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.10.0
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.7.37
  - libcurand-dev=10.3.7.37
  - libcurl=8.1.2
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.1.0
  - mpmath=1.3.0
  - mypy_extensions=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - paramiko=2.8.1
  - parso=0.8.3
  - pathspec=0.10.3
  - pcre2=10.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.4
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.10.0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytoolconfig=1.2.6
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=305
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qhull=2020.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.7.1
  - rope=1.12.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - scikit-learn=1.5.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.5.1
  - spyder-kernels=2.5.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.14
  - tomli=2.0.1
  - tomlkit=0.11.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.20348.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.2.0
  - urllib3=2.2.2
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - wrapt=1.14.1
  - xz=5.4.6
  - yaml=0.2.5
  - yapf=0.40.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - ace-tools==0.0
      - alembic==1.13.3
      - altgraph==0.17.4
      - colorlog==6.8.2
      - decorator==4.4.2
      - et-xmlfile==2.0.0
      - factor-analyzer==0.5.1
      - ffmpeg-python==0.2.0
      - flatbuffers==24.3.25
      - fsspec==2025.2.0
      - future==1.0.0
      - greenlet==3.1.1
      - hyperopt==0.2.5
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - imbalanced-learn==0.12.3
      - jax==0.4.31
      - jaxlib==0.4.31
      - krippendorff==0.8.1
      - lap==0.5.12
      - lightgbm==4.5.0
      - llvmlite==0.43.0
      - mako==1.3.5
      - mediapipe==0.10.14
      - ml-dtypes==0.4.0
      - moviepy==1.0.3
      - natsort==8.4.0
      - nuitka==2.7.10
      - numba==0.60.0
      - opencv-contrib-python==4.10.0.84
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - optuna==4.0.0
      - ordered-set==4.1.0
      - pandas-flavor==0.6.0
      - patsy==0.5.6
      - pefile==2023.2.7
      - pingouin==0.5.5
      - plotly==5.24.1
      - plotly-express==0.4.1
      - proglog==0.1.10
      - progressbar2==4.5.0
      - protobuf==4.25.5
      - py-cpuinfo==9.0.0
      - pygam==0.9.1
      - pygame==2.6.1
      - pyinstaller==6.14.1
      - pyinstaller-hooks-contrib==2025.5
      - pykalman==0.10.1
      - pynndescent==0.5.13
      - python-utils==3.9.0
      - python-vlc==3.0.21203
      - pywavelets==1.8.0
      - scikit-base==0.12.3
      - scikit-posthocs==0.10.0
      - scipy==1.11.4
      - shap==0.46.0
      - shap-hypetune==0.2.7
      - slicer==0.0.8
      - sounddevice==0.5.0
      - sqlalchemy==2.0.35
      - statsmodels==0.14.2
      - sympy==1.13.1
      - tenacity==9.0.0
      - torch==2.6.0
      - torchaudio==2.4.0
      - torchvision==0.21.0
      - ultralytics==8.3.78
      - ultralytics-thop==2.0.14
      - umap-learn==0.5.7
      - xarray==2025.3.1
      - zstandard==0.23.0
prefix: C:\Users\z984222\AppData\Local\anaconda3\envs\mediapip_torch
